#!/usr/bin/env python3
"""Generate the permutation feature-importance LaTeX tables (appendix).

One table per CMAT variant; per horizon, the top-10 features ranked by
permutation importance (ΔRMSE). Reads the live FI CSVs, so rerunning after
CMAT-Full's FI exists adds its table automatically.

Usage (from repo root):
    .venv/bin/python3 src/analysis/generate_fi_tables.py > reports/feature_importance_tables.tex
"""

import os

import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CR = os.path.join(REPO, "src", "models", "cmat", "results")
HORIZONS = [60, 120, 180]
TOP_N = 10

VARIANTS = [("tab", "CMAT-Tab"), ("ntl", "CMAT-NTL"), ("full", "CMAT-Full")]


def tex_feat(name):
    return r"\texttt{" + name.replace("_", r"\_") + "}"


print(r"""\section{Feature Importance}
\label{sec:apx:feat_imp}
% Generated by src/analysis/generate_fi_tables.py — do not hand-edit.
% Permutation feature importance under the leakage-fixed pipeline
% (13-month ROCV, per-fold PCA, final searched configs).
""")

for key, label in VARIANTS:
    paths = {h: os.path.join(CR, f"feature_importance_{key}_h{h}d.csv") for h in HORIZONS}
    if not all(os.path.exists(p) for p in paths.values()):
        print(f"% {label}: feature-importance results pending — table omitted.\n")
        continue

    tops = {}
    for h in HORIZONS:
        df = pd.read_csv(paths[h]).sort_values("importance_rmse", ascending=False)
        tops[h] = df.head(TOP_N).reset_index(drop=True)

    print(r"""\begin{table}[h]
\centering
\scriptsize
\caption{Permutation feature importance for """ + label + r""" (top-10
features per horizon, ranked by $\Delta$RMSE). Importance is the increase in
test RMSE when a feature is shuffled across test samples (10 repeats, fold~0,
seed~42), using the final Optuna-selected configuration under the
leakage-fixed pipeline. \texttt{pca\_fold\_k} denotes the $k$-th per-fold PCA
component of the raw CBS/KNMI covariates. Where the feature set includes the scalar NTL aggregate, its rank and $\Delta$RMSE are reported in the bottom row regardless of whether it enters the top-10.}
\label{tab:feat_imp_""" + key + r"""}
\begin{tabular}{r l r l r l r}
\toprule
 & \multicolumn{2}{c}{\textbf{H = 60d}} & \multicolumn{2}{c}{\textbf{H = 120d}} & \multicolumn{2}{c}{\textbf{H = 180d}} \\
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
\textbf{Rank} & \textbf{Feature} & \textbf{$\Delta$RMSE} & \textbf{Feature} & \textbf{$\Delta$RMSE} & \textbf{Feature} & \textbf{$\Delta$RMSE} \\
\midrule""")

    for i in range(TOP_N):
        cells = []
        for h in HORIZONS:
            row = tops[h].iloc[i]
            cells += [tex_feat(row["feature"]), f"{row['importance_rmse']:.1f}"]
        print(f"{i + 1} & " + " & ".join(cells) + r" \\")

    # Dedicated row for the scalar NTL aggregate (shown regardless of rank),
    # for variants whose feature set includes it.
    ntl_parts = []
    for h in HORIZONS:
        df = pd.read_csv(paths[h]).sort_values("importance_rmse", ascending=False).reset_index(drop=True)
        hit = df[df["feature"] == "ntl_a2_all_mean"]
        if len(hit) == 0:
            ntl_parts = []
            break
        rank = int(hit.index[0]) + 1
        val = float(hit["importance_rmse"].iloc[0])
        sign = "+" if val >= 0 else "-"
        ntl_parts.append(f"rank {rank} (${{{sign}}}{abs(val):.1f}$) at {h}d")
    if ntl_parts:
        print(r"\midrule")
        print(r"\multicolumn{7}{l}{\textit{NTL scalar} \texttt{ntl\_a2\_all\_mean}: "
              + ";\; ".join(ntl_parts) + r"} \\")

    print(r"""\bottomrule
\end{tabular}
\end{table}
""")

print(r"\clearpage")
