#!/usr/bin/env python3
"""Generate the permutation feature-importance LaTeX tables (appendix).

One table per CMAT variant; per horizon, the top-10 features ranked by
permutation importance (ΔRMSE). Reads the live FI CSVs, so rerunning after
CMAT-Full's FI exists adds its table automatically.

Usage (from repo root):
    .venv/bin/python3 src/analysis/generate_fi_tables.py > reports/feature_importance_tables.tex
"""

import os

import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CR = os.path.join(REPO, "src", "models", "cmat", "results")
# h120 deferred from the study scope (2026-08-29).
HORIZONS = [60, 180]
TOP_N = 10

VARIANTS = [("tab", "CMAT-Tab"), ("ntl", "CMAT-NTL"), ("full", "CMAT-Full")]


def tex_feat(name):
    return r"\texttt{" + name.replace("_", r"\_") + "}"


print(r"""\section{Feature Importance}
\label{sec:apx:feat_imp}
% Generated by src/analysis/generate_fi_tables.py — do not hand-edit.
% Permutation feature importance under the leakage-fixed pipeline
% (13-month ROCV, per-fold PCA, final searched configs).
""")

for key, label in VARIANTS:
    paths = {h: os.path.join(CR, f"feature_importance_{key}_h{h}d.csv") for h in HORIZONS}
    if not all(os.path.exists(p) for p in paths.values()):
        print(f"% {label}: feature-importance results pending — table omitted.\n")
        continue

    tops = {}
    for h in HORIZONS:
        df = pd.read_csv(paths[h]).sort_values("importance_rmse", ascending=False)
        tops[h] = df.head(TOP_N).reset_index(drop=True)

    print(r"""\begin{table}[h]
\centering
\scriptsize
\caption{Permutation feature importance for """ + label + r""" (top-10
features per horizon, ranked by $\Delta$RMSE). Importance is the increase in
test RMSE when a feature is shuffled across test samples (10 repeats, fold~0,
seed~42), using the final Optuna-selected configuration under the
leakage-fixed pipeline. \texttt{pca\_fold\_k} denotes the $k$-th per-fold PCA
component of the raw CBS/KNMI covariates. Where the model's inputs include the scalar NTL aggregate or the 2D NTL image modality (all spatial patches shuffled jointly), its rank and $\Delta$RMSE are reported in a bottom row regardless of whether it enters the top-10.}
\label{tab:feat_imp_""" + key + r"""}
\begin{tabular}{r """ + "l r " * len(HORIZONS) + r"""}
\toprule
 & """ + " & ".join(r"\multicolumn{2}{c}{\textbf{H = " + str(h) + r"d}}" for h in HORIZONS) + r" \\" + "\n"
      + " ".join(r"\cmidrule(lr){" + f"{2 + 2 * i}-{3 + 2 * i}" + "}" for i in range(len(HORIZONS))) + "\n"
      + r"\textbf{Rank}" + r" & \textbf{Feature} & \textbf{$\Delta$RMSE}" * len(HORIZONS) + r" \\" + "\n"
      + r"\midrule")

    for i in range(TOP_N):
        cells = []
        for h in HORIZONS:
            row = tops[h].iloc[i]
            cells += [tex_feat(row["feature"]), f"{row['importance_rmse']:.1f}"]
        print(f"{i + 1} & " + " & ".join(cells) + r" \\")

    # Dedicated bottom rows for the NTL inputs (shown regardless of rank),
    # for variants whose inputs include them: the scalar aggregate
    # (CMAT-NTL) and the 2D image modality as a whole (CMAT-Full).
    n_cols = 1 + 2 * len(HORIZONS)
    for feat_name, row_label in (
        ("ntl_a2_all_mean", r"\textit{NTL scalar} \texttt{ntl\_a2\_all\_mean}"),
        ("ntl_images", r"\textit{NTL 2D imagery (all patches)} \texttt{ntl\_images}"),
    ):
        parts = []
        for h in HORIZONS:
            df = pd.read_csv(paths[h]).sort_values("importance_rmse", ascending=False).reset_index(drop=True)
            hit = df[df["feature"] == feat_name]
            if len(hit) == 0:
                parts = []
                break
            rank = int(hit.index[0]) + 1
            val = float(hit["importance_rmse"].iloc[0])
            sign = "+" if val >= 0 else "-"
            parts.append(f"rank {rank} (${{{sign}}}{abs(val):.1f}$) at {h}d")
        if parts:
            print(r"\midrule")
            print(r"\multicolumn{" + str(n_cols) + r"}{l}{" + row_label + ": "
                  + ";\; ".join(parts) + r"} \\")

    print(r"""\bottomrule
\end{tabular}
\end{table}
""")

print(r"\clearpage")
